37 api authentication phase 2
malgo-ia/rating-room pull request #39
Opened 2023-07-13 09:33 UTC by malgo-ia

Please verify and comment.

2023-07-13 12:57 UTC, ginone requested changes

2023-07-13 12:57 UTC, ginone commented on tests/utils/utils.py
> +print(token_generator(16))
to cleanup

2023-07-13 12:57 UTC, ginone commented on app/test_draft/testy_put_login_manual.py
> +import random
to cleanup (whole file)

2023-07-13 12:57 UTC, ginone commented on .github/workflows/pytest_and_docker_image.yml
> +      env:
to cleanup (whitespace)

2023-07-13 12:57 UTC, ginone commented on app/endpoints/users_endpoints.py
> +            return web.json_response({"error": str(e)}, status=400)
it's a bad practice to return stack traces (`str(e)`) from database operations. we do not want hacker to learn about our database implementation (engine, version, table names, column names, etc)

please change errors to some generic messages in `try/except` blocks that perform db operations

2023-07-13 12:57 UTC, ginone commented on app/services/users_services.py
> +            "exp": datetime.utcnow() + timedelta(minutes=15),
eventually we will likely want to increase session to longer period, maybe even 24h?

2023-07-13 13:53 UTC, malgo-ia commented
Please check PR corrections. 
By mistake I also added changes related to  Issue #12 DB Session Middleware . Please let us close these two Issues together. Sorry for the inconvenience :)

2023-07-15 10:31 UTC, ginone requested changes

2023-07-15 10:31 UTC, ginone commented on app/services/users_services.py
> +def verify_credentials(db_session, login: str, password: str) -> str:
IMO   "verify credentials" should  only verify credentials (basically return True or False),  creatingn JWT is separate resposibility, should be separate funnctionn

2023-08-02 17:37 UTC, ginone approved these changes

2023-08-02 17:37 UTC, merged